define

calledQualifiedName sub attribute, datatype string;
calledUri sub attribute, datatype string;
kytheUri sub attribute, datatype string;

JavaMethodDeclaration
    has kytheUri;

JavaMethodInvocation
    has calledQualifiedName,
    has calledUri;
