name: Release
on:
  release:
    types: [prereleased, released]

jobs:

  release:
    name: Publish Package
    runs-on: ubuntu-latest
    steps:

      - name: Fetch Sources
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Clean & Build
        run: ./gradlew clean build -x test
        env:
          GITHUB_ACTOR: ${{ secrets.PHENOMENA_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.PHENOMENA_TOKEN }}

      - name: Publish Package
        run: ./gradlew publish
        env:
          GITHUB_ACTOR: ${{ secrets.PHENOMENA_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.PHENOMENA_TOKEN }}
